### ISSUE TITLE
PB1.4: Schedule Database

### ISSUE THREAD

**Issue by lydialegan** [Yash-Jajam/Student_App#12]
Create a MySQL database that will hold a table with the following information:
Unique Student ID (linked to: course ID, course name, course dates, course times, course location)

The database is free of errors and displays accurately in React
The code reads and pulls data from the database without issues
Data is not changed or added when used in the code

**Comment by Yash-Jajam** [comment]
![Image](https://github.com/user-attachments/assets/6fe9c353-5a99-4c3e-bcd9-c7b490baf9b6)

Local database created in MySQL and data has been inserted into the student table.

But we are not going to use this setup as the API integration is currently not in our scope and we have opted to just hardcode some values into a local file within the project folder from which we will pull the student and class details.
