### ISSUE TITLE
PB5.2: Back-end File Setup

### ISSUE THREAD

**Issue by lydialegan** [Yash-Jajam/Student_App#23]
Back-end File Setup: Implement Node.js/Express back-end to connect with MySQL database.

- [x] Project structure: Organize back-end projects with clear folder structures to separate concerns and ensure maintainability.

- [x] Server Connection Validation: 
Confirm the server successfully connects to the MySQL database on start up
Confirm the server starts without errors
Test and confirm the connection is closed or re-established appropriate based on connection status.

- [x] Testing: Perform manual testing in development to verify expected behavior and address any unexpected results.

**Document the back-end setup process, including server start instructions, environment variable setup, and configuration details for connecting to the MySQL database in the comments below.**

**Comment by Yash-Jajam** [comment]
![Image](https://github.com/user-attachments/assets/65c6c191-2549-4d16-82f0-2211be4dc7f8)
![Image](https://github.com/user-attachments/assets/c3160389-9ead-4e9f-81a3-e1e4f071036d)
![Image](https://github.com/user-attachments/assets/5663db8e-31e5-4867-84aa-8994176973ff)

The MySQL database (3306) and Express app (port: 3000) are communicating successfully and we can see the correct data being shown when we enter http://localhost:3000/users?student_id=102 in the browser.

**Comment by Yash-Jajam** [comment]
![Image](https://github.com/user-attachments/assets/5dc96e48-6c12-4156-a0ea-49ad17fc9824)

**Comment by ugoetudo** [comment]
> ![Image](https://github.com/user-attachments/assets/5dc96e48-6c12-4156-a0ea-49ad17fc9824)

Awesome to see! Well done.
